Kubernetes controllers.HW#2
otus-kuber-2020-04/volkmydj_platform pull request #4
Opened 2020-05-09 14:49 UTC by volkmydj

# Выполнено ДЗ №2

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Создал кластер kind.
 - Создал манифест для запуска одной реплики приложения frontend.
 - Собрал образ для сервиса paymentservice и запушил две версии в docker hub.
 - Создал манивест для запуска 3-х реплик сервиса paymentservice версии 0.0.1.
 - Создал деплоймент на основании манифеста реплики сервиса paymentservice и запустил его.
 - Обновил деплоймент до версии 0.0.2.
 - Сделал RollBack деплоймента до версии 0.0.1.
 - Создал два манифеста с технологией обновления микросервисов: аналог blue-green и reverse rolling update.
 - На основании микросервиса frontend реализовал механизм проверки работоспособности приложения при помощи probes.
 - Создал манифест DaemonSet для экспортера Node Exporter.
 - Манифест NodeExporter модернизировал так,чтобы Node Exporter разворачивался как на worker нодах, так и на master нодах.

## Как запустить проект:
 - `cd kebernetes-controllers`
 - `kubectl apply -f frontend-deployment.yaml`
 - `kubectl apply -f frontend-paymentservice.yaml`
 - `kubectl apply -f node-exporter-daemonset.yaml` 

## Как проверить работоспособность:
 -  `kubectl get pods`

## PR checklist:
 - [x] Выставлен label с темой домашнего задания

2020-05-10 21:24 UTC, Jasstkn requested changes
Добрый вечер! Домашнее задание выполнено верно! Здорово, что уделяете время заданиям со звездочками - они самые важные для хорошего усвоения материала =) По node-exporter оставила вам комментарий для дальнейших разбирательств, если что пишите в чат в слаке по вопросам. Также, хочу попросить вести чуть более подробный ридми, а именно команды для проверки с их аутпутом и если были сделаны изменения в манифестах, тоже отражайте их пожалуйста - это облегчит проверку и также поможет сформировать навык подробного ведения ченджлога. Хорошего вечера и буду ждать исправлений по node exporter!

2020-05-10 21:24 UTC, Jasstkn commented on kubernetes-controllers/node-exporter-daemonset.yaml
> +          effect: NoSchedule
Вы начали копать в нужную сторону, но не совсем верно определили tolerations.
Предлагаю вам подробнее ознакомиться с документацией:
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#concepts -> секция Note и с официальным манифестом для node exporter.

2020-05-10 22:13 UTC, volkmydj commented on kubernetes-controllers/node-exporter-daemonset.yaml
> +          effect: NoSchedule
Спасибо за замечания)
Я разобрался, что я сделал не совсем так

2020-05-11 08:31 UTC, Jasstkn commented on kubernetes-controllers/node-exporter-daemonset.yaml
> +          effect: NoSchedule
Отлично! Теперь все, как говорится, в лучшем виде - аппру =)

2020-05-11 08:31 UTC, Jasstkn approved these changes

2020-05-11 08:31 UTC, merged